import type { IApi, IDumiTechStack } from '@/types';

class HiddenReactTechStack implements IDumiTechStack {
  name = 'hidden-react';

  runtimeOpts = {};

  isSupported() {
    return true;
  }

  transformCode(raw: string) {
    return raw;
  }

  generatePreviewerProps(props: any) {
    props.description = 'generated by hidden tech stack';
    return props;
  }
}

export default function hiddenTechStackPlugin(api: IApi) {
  api.registerTechStack(() => new HiddenReactTechStack());
}
